
# PromiseAlreadyResolvedException

This exception is thrown when the user tried to reject or fulfill a promise,
after either of these actions were already performed.



* Full name: `\Sabre\Event\PromiseAlreadyResolvedException`
* Parent class: [`LogicException`](../../LogicException.md)






***
> Automatically generated on 2025-03-18
